version: "3.9"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Admin
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABSE: db_test
    volumes: 
      - ./data/db
